Feature/AC-53 and AC-57
bq-educacion/academy-manager pull request #13
Opened 2022-07-26 13:02 UTC by pruizj

query: getCenters sin filtros todavia y getCenter por id
mutation: createCenter y addContactCenter

2022-07-26 14:58 UTC, aldaMarMu requested changes
¡Buen trabajo! :smile: :clap: 
Te he puesto cosillas de buenas prácticas y algunos detalles de los modelos y esquemas :)

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
>  export const typeDefs = gql`
Te recomiendo que hagas una carpeta `schemas` y que separes los schemas por tipos/queries lo que veas que te gusta más, porque si no este fichero crecerá tantísimo que será muy tedioso trabajar con él.
Yo normalmente los hago por tipo y funciones de ese tipo, por ejemplo: fichero que se llame center.ts y que tenga type Center y getCenters, getCenter, createCenter, editCenter.... y así con todo

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
> +    getCenters:[Center!]!
ojo, esta query dará error hasta que no haya un centro metido y al principio seguro seguro que no va a haber ninguno. El tipo correcto sería `[Center!]` para que pueda devolver un array vacío, pero que cuando haya al menos un ítem este tenga que ser un Center.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
> +    addContactCenter(idCenter:String!,name:String!,surname:String!, email:String!, phone:String!): String!
Normalmente en Graphql en las mutations se devuelve el tipo que estás creando/editando para que el front si quiere, actualice los datos directamente con lo que le devuelve la operación sin necesidad de hacer más llamadas.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +      notes: string;
En el types.ts tienes un tipo `MutationCreateCenterArgs` que debería tener los mismos campos que has puesto tu aquí a mano. (Estos deberían ser iguales que los del schema y el types se genera a partir de ahí).
Todo lo que esté automatizado mejor cogerlo de ahí, para que luego sea mucho más fácil si hay que actualizar algo.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +    const centerCollection = db.collection<CenterModel>("centers");
Para no tener que hacer esto en cada resolver, yo lo pondría con los models y así importas ya directamente el CenterCollection.
En models tendrías que poner `const CenterCollection = (db) => db.collection<CenterModel>("centers");` y allá donde lo uses `CenterCollection(ctx.db).find(....)`, con find o con el método que quieras.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +    const centerCollection = db.collection<CenterModel>("centers");
En models cuando vaya habiendo más modelos y colecciones seguramente también ayude poner un fichero por cada tipo/colección, para tenerlos más organizados.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +      notes: args.notes,
puedes hacer `...args` y te coge por defecto los parámetros que le lleguen en el args. Lo que sí que creo que estaría bien es hacer el tipo primero, tipado como ICenterModel y luego ya hacer el insertOne del objeto tipado.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +    },
Lo mismos para todas las Queries / mutations, coge el tipo de los argumentos del fichero autogenerado.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/query.ts
> +    return centers;
aquí si no haces ninguna comprobación de errores puedes devolver directamente `return centerCollection.find().toArray();`

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/query.ts
> +  getCenters: async (_parent: unknown, _args: unknown, ctx: Context) => {
mejor tipar lo que devuelven las queries desde el principio :) :Promise<ICenterModel[]>

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
> +  type Center{
Lo pongo aquí, pero aplica a todo, mucho cuidado con poner campos obligatorios.... Si son obligatorios en el schema, una vez que el objeto exista en BD tiene que tener TODOS los items. Si desde UX/UI se ha planteado que en el formulario haya campos obligatorios bien, si no es obligatorio meterlos y aquí sí lo son, dará errores al ejecutar cualquier query.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
> +    platformEducationExperience: [String]
En general, los arrays se tipan siempre así: `[typeXX!]`, para que puedan no existir, pero en caso de que exista algún item, esté bien tipado. (A no ser que el campo sea obligatorio sí o sí y siempre deba tener al menos un valor, entonces ahí se obligarían las dos cosas `[typeXXX!]!`)

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/schema.ts
> +  enum State{
Los enums y los Types son comunes a tooodos los campos del esquema, así que mejor si son descriptivos de a quién se refieren... Entiendo que en este caso es del Monitor? o del Alumno? O va a ser el mismo para todos? igual también vendría bien especificarlo

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/query.ts
> +  id: (parent: CenterModel): string => {
Dentro del tipo Center de graphql tienes campos que no son lo que se guarda en base de datos, por ejemplo los grupos. En la base de datos se guardarán los IDs y tu al front le quieres pasar el tipo Grupo, por lo que aquí tendrás que meter todos esos campos que se guardan distintos de lo que se mandan. Igual para cuando hagas los resolvers de los Monitores o los Grupos, tendrás campos que tienes que resolver aquí a mano.
En este caso, para los grupos debería ser algo así: `groups: async (parent) => GroupCollection.find({_id: {$in: parent.groups}}).toArray()`

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/models/models.ts
> +  _id?: ObjectId;
en este modelo también tendrías que omitir groups del tipo autogenerado y especificar aquí que es un array de ids.

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/models/models.ts
> +  center: ObjectId;
aquí, además de center, guardarás con ids los campos de instructors y students. Repasa esto de los campos del esquema :)

2022-07-26 14:58 UTC, aldaMarMu commented on packages/api_bo/src/models/models.ts
> +};
De momento se puede quedar así, pero piensa bien si es necesario guardar un array de instructors en los grupos y luego además guardar un array de grupos en cada instructor... Creo que es repetir mucha información. (Igual para los grupos y alumnos)

2022-07-29 09:34 UTC, avalero commented on packages/api_bo/src/schema.ts
> +    getCenters:[Center!]!
@aldaMarMu creo que esto es correcto. Porque si no hay centros devolverá array vacío, que es válido.

Si no fuerzas el array el front deberá comprobar siempre si es array para que no de error de tipado

2022-08-01 11:35 UTC, aldaMarMu commented
La cierro, que está todo en la otra PR https://github.com/bq-educacion/academy-manager/pull/15

2022-08-01 11:35 UTC, closed without merging