Feature/error pages
bq-educacion/academy-manager pull request #14
Opened 2022-07-29 08:51 UTC by YBlas

2022-08-02 11:34 UTC, CarmenDomin requested changes

2022-08-02 11:34 UTC, CarmenDomin commented on packages/ui/src/components/MainButton.tsx
> +function useRouter() {
Esto se te ha colado :)

2022-08-02 11:34 UTC, CarmenDomin commented on packages/ui/src/components/SecondActionButton.tsx
> +import { Bell } from "@academy-manager/ui/src/assets/icons";
Hay un componente `Icon` para centralizar todos los iconos y envolverlos en un componente que pueda darles color u otras propiedades. Tienes que exportar en `Icon` todos los iconos que hayas creado (puedes borrar el que metí yo si no lo usas), y luego meterlos en el `switch`, y para usarlos:

`<Icon name="bell" />`

2022-08-02 11:34 UTC, CarmenDomin commented on packages/front_bo/components/ErrorContent.tsx
> +import { P2, P4, PG } from "@academy-manager/ui/src/theme/styles";
No debes exportar así las cosas de ui, de una librería sólo debe usarse lo que se esté exportando en su `index` (de forma que si cambias la estructura de carpetas de ui no afectes al resto del proyecto), deberías añadir `P1`, `P2`... al index de `theme`, y como `theme` está en el index ppal de ui ya solo sería hacer:

```
import { styles } from "@academy-manager/ui";

const { P2, PG } = styles;
```

2022-08-02 11:34 UTC, CarmenDomin commented on packages/front_bo/components/ErrorContent.tsx
> +import { MButton } from "@academy-manager/ui/src/components/MainButton";
Lo mismo con los componentes, si metes todos los componentes que has creado en el index de `components`, como `components` ya está en el index principal los podrás importar con:

```
import { MainButton } from "@academy-manager/ui";
```

2022-08-02 11:34 UTC, CarmenDomin commented on packages/front_bo/components/ErrorContent.tsx
> +import { MButton } from "@academy-manager/ui/src/components/MainButton";
Una vez importes todo de `@academy-manager/ui` podrás simplificar el import:

```
import { colors, MainButton, styles } from "@academy-manager/ui";
```

2022-08-02 11:34 UTC, CarmenDomin commented on packages/ui/src/theme/styles.tsx
> +export const PG = styled.p`
Cero problema con que crees un P por cada tipo de fuente, pero porsi no se te había ocurrido te cuento, como `fonts` se está exportando de ui podrías directamente usar en `ErrorContent` la fuente en el `p` que quisieras.

Además ten en cuenta que en `base-styles` se está metiendo a todo `${fonts.family.roboto};` y `color: ${colors.colors.black};`

2022-08-02 11:34 UTC, CarmenDomin commented on packages/ui/src/components/SecondActionButton.tsx
> +import { Bell } from "@academy-manager/ui/src/assets/icons";
Otra cosa, no está bien que dentro de `ui` se importen cosas de `ui`, aquí sí debería hacerse por carpetas:
```
import { Bell } from "../assets/icons";
```
o cuando lo cambies a Icon:
```
import Icon from "./Icon";
```

2022-08-03 11:05 UTC, YBlas commented on packages/ui/src/components/MainButton.tsx
> +function useRouter() {
hecho

2022-08-03 11:05 UTC, YBlas commented on packages/ui/src/components/SecondActionButton.tsx
> +import { Bell } from "@academy-manager/ui/src/assets/icons";
done

2022-08-03 11:22 UTC, YBlas commented on packages/front_bo/components/ErrorContent.tsx
> +import { P2, P4, PG } from "@academy-manager/ui/src/theme/styles";
done

2022-08-03 11:22 UTC, YBlas commented on packages/front_bo/components/ErrorContent.tsx
> +import { MButton } from "@academy-manager/ui/src/components/MainButton";
done

2022-08-03 11:32 UTC, YBlas commented on packages/ui/src/theme/styles.tsx
> +export const PG = styled.p`
done

2022-08-03 12:46 UTC, CarmenDomin approved these changes
Las cositas que he visto ya son poca cosa, sobretodo es interesante la de simplificar imports :)

2022-08-03 12:46 UTC, CarmenDomin commented on packages/ui/src/assets/icons/index.ts
>  import MenuKebab from "./icon-menukebab.svg";
Esto es una bobada pero, por consistencia, quitale el `icon-` del nombre.

2022-08-03 12:46 UTC, CarmenDomin commented on packages/ui/src/components/Icon.tsx
> +import { Triangle } from "../assets/icons";
SImplifica estos imports:
```
import { ClosePannel, Bell, MenuKebab, Lens, Triangle } from "../assets/icons";
```

2022-08-03 12:46 UTC, CarmenDomin commented on packages/ui/src/components/GoogleButton.tsx
>  export const GoogleButton: FC = () => {
Si en lugar de exportar el componente de esta forma lo exportas como default:
```
const GoogleButton: (...);
export default GoogleButton;
```

Luego puedes hacer:
```
import GoogleButton from "./GoogleButton";
```

2022-08-04 07:17 UTC, YBlas commented on packages/ui/src/components/Icon.tsx
> +import { Triangle } from "../assets/icons";
Hecho

2022-08-04 07:17 UTC, YBlas commented on packages/ui/src/assets/icons/index.ts
>  import MenuKebab from "./icon-menukebab.svg";
Hecho

2022-08-04 07:17 UTC, YBlas commented on packages/ui/src/components/GoogleButton.tsx
>  export const GoogleButton: FC = () => {
Hecho

2022-08-04 08:01 UTC, merged