feature/AC-3 LogOut Popover
bq-educacion/academy-manager pull request #16
Opened 2022-08-01 10:19 UTC by YBlas

2022-08-04 14:38 UTC, CarmenDomin requested changes
Está bien! he visto un par de detalles, la carpeta de `components` de `front_bo`, además de meterla en el `src`, estaría bien si le pones un index para después importar con más sencillez, por ejemplo:
```
import { ErrorContent, LateralMenu } from "../components";
```

2022-08-04 14:38 UTC, CarmenDomin commented on packages/ui/src/components/Popover.tsx
> +export type Popoverprops = {
Camelcase: `PopoverProps`

2022-08-04 14:38 UTC, CarmenDomin commented on packages/ui/src/hooks/useClickOutside.ts
> +  effects: any[] = []
Los `any`s son peligrosos, puedes definir el tipo de alguna forma?

2022-08-05 06:24 UTC, YBlas commented on packages/ui/src/components/Popover.tsx
> +export type Popoverprops = {
Hecho, el cambio de los componentes a src y la creación del index para los mismos está hecha en la otra pr que tengo abierta solo para eso.

2022-08-05 06:35 UTC, YBlas commented on packages/ui/src/hooks/useClickOutside.ts
> +  effects: any[] = []
Ese effects estaba solo por si quería añadir más condiciones de recarga al useEffect, pero es verdad que es tontería si el único objetivo es que se lance cuándo pinches fuera, lo quito y ya está.

2022-08-05 06:45 UTC, CarmenDomin approved these changes

2022-08-05 07:12 UTC, merged