feature AC-59 and fix format createdAt
bq-educacion/academy-manager pull request #17
Opened 2022-08-02 11:34 UTC by pruizj

query de getGroups y getGroup por id sin filtros
mutation crear Grupo

2022-08-02 16:58 UTC, avalero requested changes

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +    const id_group = (await groupCollection(ctx.db).find({center:new ObjectId(args.idCenter)}).toArray()).length +1;
Creo que todos hemos hecho esto la primera vez :) pero te va a fallar. Te pongo un ejemplo

- Creas el primer grupo: le asigna el id 1 (hay 0 +1)
- Creas el segundo grupo: le asigna el id 2 (hay 1 +1)
- Creas el tercer grupo: le asigna el id 3 (hay 2   + 1)
- Borras el grupo 2
- Creas otro grupo: le asigna el id 2, porque hay 1 +1, y tendrás dos grupos con id 2

Por eso es mejor que crees los ids de mongo, o si no, te bajas todos los ids de los grupos, buscas el máximo, y le asignas +1. Los ids no serán consecutivos, pero te aseguras que no se repitan (aunque esto es feote)

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +    if(!exists || (exists.length !== instructors?.length)) throw new Error('404, Instructors not found');
exists siempre va a exsite (es decir, nunca se va a cumplir !exists) dado que te dará array vació, pero no undefined. En cualquier caso typescript te permitiría hacer eso en una sola sentencia `if(exists?.lenght !== ...)`, jeje, por eso es bueno hacerse el curso de TypeScript, sé que soy muy académico, pero creo que realmente vale la pena :)

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +      instructors: instructors || [],
cuado la clave y el valor se llaman ingual no hace falta ponerlo dos veces, valdría:
```
{
      ...args,
      id_group:id_group,
      center,
      createdAt,
      instructors: instructors || [],
      ....
}
```

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/query.ts
> +  getGroups: async (_parent: unknown, _args: unknown, ctx: Context) => {
no olvides tipar el valor de retorno

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/query.ts
> +  ) => {
no olvides tipar el valor de retorno

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/query.ts
> +    });
para no tener que hacer siempre esto podrías crear una función dentro de la colección que sea `findById` y que le puedas pasar directamente el string.

Sería algo de este tipo para cada colección (en la función que ya tienes:
```
export const centerCollection = (db: Database) => {
  const collection = db.collection<CenterModel>("centers");
  collection.prototype.findById = async function(id: string): Promise<CenterModel>{
     return await collection.findOne({_id: new ObjectId(id)})
  }
  return collection;
}
```
(algo así, habría que probarlo, pero se puede, y te hará el código más limpio)

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/resolvers/query.ts
> +  center: async (parent: GroupModel, _:unknown, ctx: Context) => {
no olvides tipar el retorno

2022-08-02 16:58 UTC, avalero commented on packages/api_bo/src/schemas/group.ts
> +        getGroups:[Group!]
`getGroups: [Group!]!`

2022-08-03 07:33 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
> +    const id_group = (await groupCollection(ctx.db).find({center:new ObjectId(args.idCenter)}).toArray()).length +1;
Estoy de acuerdo con lo que dice Alberto :)
Solo un apunte por si en algún momento en el futuro quieres contar cuántos items hay de algo en mongo, en vez de `find` puedes usar `countDocuments(filter)` con el mismo filtro que le pasarías al find y te devuelve el número directamente :smile:

2022-08-03 16:52 UTC, avalero commented
Hola @pruizj está muy bien, te he puesto alguna cosillas pequeñas y estaría listo.

He visto que has corregido el resto de comentarios. Para ayudar al revisor, siempre que corrijas o cambies algo contesta al comentario, por ejemplo poniendo "hecho!", de ese modo ayudas a los compañeros a revisar el código.

2022-08-03 16:52 UTC, avalero requested changes

2022-08-03 16:52 UTC, avalero commented on packages/api_bo/src/schemas/group.ts
> +        timetable: [Timetable!]
un grupo podría no tener horario? si siempre va a tener horario entonces `[]!`
lo mismo para el resto de campos, los que sean obligatorios deben estar siempre marcados con `!`

2022-08-04 06:33 UTC, pruizj commented on packages/api_bo/src/schemas/group.ts
> +        timetable: [Timetable!]
Hecho

2022-08-04 06:50 UTC, avalero approved these changes

2022-08-04 06:51 UTC, merged