feature/modular layout
bq-educacion/academy-manager pull request #28
Opened 2022-08-08 08:14 UTC by YBlas

2022-08-08 10:51 UTC, CarmenDomin requested changes

2022-08-08 10:51 UTC, CarmenDomin commented on packages/front_bo/src/components/Layout.tsx
> +        <ContentStart section={section} label={label} children={children} />
El parámetro `children` se suele pasar así:
```
        <ContentStart section={section} label={label}>{children}</ContentStart>
```

2022-08-08 10:51 UTC, CarmenDomin commented on packages/front_bo/src/components/Layout.tsx
> +  children: ReactNode;
Si haces que children sea opcional luego no tienes porqué poner `children={undefined}` en las páginas de error.

2022-08-08 10:51 UTC, CarmenDomin commented on packages/front_bo/src/components/LateralMenu.tsx
>    sections: {
Si en el config defines los tipos luego aquí te ahorras reescribirlos:
```
type ILink = {
  label: string;
  href: string;
}

export type ISection = {
  title: string;
  links: ILink[]
}

export const sections: ISection[] = [{
   ...
}];
```
```
type LateralMenuProps = {
  sections: ISection[];
};
```

2022-08-08 10:51 UTC, CarmenDomin commented on packages/front_bo/src/components/LateralMenu.tsx
>                  setClicked(!clicked);
Si esto lo haces así cuando se entre por url a una página el menú no va a saber en qué sección se encuentra, tienes que pasarle al `LateralMenu` las variables de `section` y `label`, y que sean esas variables las que determinen la sección y subsección activas.

2022-08-08 10:51 UTC, CarmenDomin commented on packages/ui/src/components/GoogleButton.tsx
> +    cursor: pointer;
El cursor siempre se muestra en hover, es decir, no hace falta definirlo dentro de `hover`, si lo defines en el componente en general también funcionará bien

2022-08-10 08:47 UTC, YBlas commented on packages/front_bo/src/components/Layout.tsx
> +        <ContentStart section={section} label={label} children={children} />
hecho

2022-08-10 08:47 UTC, YBlas commented on packages/front_bo/src/components/LateralMenu.tsx
>    sections: {
hecho

2022-08-10 08:52 UTC, YBlas commented on packages/ui/src/components/GoogleButton.tsx
> +    cursor: pointer;
done

2022-08-10 08:53 UTC, YBlas commented on packages/front_bo/src/components/Layout.tsx
> +  children: ReactNode;
done

2022-08-10 10:01 UTC, YBlas commented on packages/front_bo/src/components/LateralMenu.tsx
>                  setClicked(!clicked);
done

2022-08-10 14:25 UTC, CarmenDomin approved these changes

2022-08-11 06:58 UTC, merged