feature/AC-59-order
bq-educacion/academy-manager pull request #33
Opened 2022-08-10 11:14 UTC by pruizj

2022-08-10 11:52 UTC, aldaMarMu commented on packages/api_bo/src/lib/paginatedFilters.ts
> +              { $lookup: {from: "instructors", localField: "instructors", foreignField: "_id", as: "instructorsName"}},
mete esto solo cuando tengas que ordenar por nombre de centro o instructor, que al ser una query genérica no siempre vas a necesitar esos campos.

2022-08-11 08:09 UTC, pruizj commented on packages/api_bo/src/lib/paginatedFilters.ts
> +              { $lookup: {from: "instructors", localField: "instructors", foreignField: "_id", as: "instructorsName"}},
Hecho

2022-08-11 08:34 UTC, aldaMarMu commented on packages/api_bo/src/lib/paginatedFilters.ts
> +  check:string,
este argumento se lo vas a pasar siempre siempre? Por si es mejor ponerlo opcional.
Si además luego vas a poner ifs que comparen con valores concretos yo lo tiparía como `check: "centers" | "groups"`

2022-08-11 08:40 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/query.ts
> -  getCenters: async (
por qué le quitas el async?

2022-08-11 08:45 UTC, aldaMarMu requested changes
Al crear grupo para poder probar el filtro me da error... 
`"Http failure response for http://localhost:6005/graphql: 0 Unknown Error"`
`error: Uncaught (in promise) TypeError: Cannot convert object to primitive value`
¿Puede ser porque no haya instructores? Si no tengo monitores creados... qué le paso? En ningún caso el servidor debería explotar, porque ahora mismo tengo que reiniciarlo para poder seguir haciendo cosas.
Esta es la mutation que le estoy mandando:

```
mutation CR_GROUP{
  createGroup(
    idCenter: "62f4be7ad3cba5532fa049f3"
    name: "grupo 1"
    type: INTERNAL
    course: "1"
    timetable: [{ day: MONDAY, start: "12", end: "14" }]
    notes: "patata",
  ) {
    id
}}
```

2022-08-11 11:04 UTC, pruizj commented on packages/api_bo/src/lib/paginatedFilters.ts
> +  check:string,
hecho

2022-08-11 11:04 UTC, pruizj commented on packages/api_bo/src/resolvers/query.ts
> -  getCenters: async (
hecho

2022-08-11 11:08 UTC, aldaMarMu approved these changes
¡funciona bien :partying_face: !

Lo de controlar que no pete el servidor acostúmbrate a hacerlo en todas las llamadas a mongo que modifiquen contenido, repasa por si hubiera alguna por ahí que se haya colado (aunque sea en la siguiente PR)

2022-08-11 11:09 UTC, merged