Feature/table
bq-educacion/academy-manager pull request #45
Opened 2022-08-16 11:20 UTC by YBlas

Changes on back types to avoid null data return.
Basic table working

2022-08-16 12:13 UTC, empoalp approved these changes
Algunos comentarios minor

2022-08-16 12:13 UTC, empoalp commented on packages/front_bo/src/pages/extra/centers.tsx
> +    {
este par de llaves sobran

2022-08-16 12:13 UTC, empoalp commented on packages/front_bo/src/pages/extra/centers.tsx
> +  {
Este par de llaves sobran
creo que sería más claro de leer

    if (error) {
      route.push("/500");
    }

2022-08-16 12:13 UTC, empoalp commented on packages/front_bo/src/pages/extra/centers.tsx
> +    <>
No necesitas este Fragment. El único hijo es El Layout

2022-08-16 15:12 UTC, avalero commented on packages/front_bo/src/pages/extra/centers.tsx
> +                label: t("components.column.name"),
El componente ya no se llama column (si es que el literal es así por el nombre del componente). Esto está en la página `centers`

2022-08-16 15:28 UTC, avalero requested changes
Hola @YBlas , te he puesto algún comentario. 2 importantes:

1. No has subido el componente Table.
2. Has tratado`languages` como si fuera un `string`, pero es un `string[]`

2022-08-16 15:28 UTC, avalero commented on packages/front_bo/src/pages/extra/centers.tsx
> +                content: (item) => <div>{item.languages}</div>,
¿no habías dicho que languages es un array de string? ojo a estos detalles. estos errores no puedes cometerlos.

2022-08-16 15:28 UTC, avalero commented on packages/front_bo/src/pages/extra/centers.tsx
> +            {data && data.getCenters.data?.length && (
No hace falta que uses `length`, ¿cuál es el objetivo?

2022-08-16 15:28 UTC, avalero commented on packages/front_bo/src/pages/extra/centers.tsx
> +        {data && !data.getCenters.data?.length && !loading && (
si tienes `data` entonces siempre `!loading`, no tiene sentido usar ambos. Además, no es necesario que mires `length`, ¿para qué?

2022-08-17 07:10 UTC, YBlas commented on packages/front_bo/src/pages/extra/centers.tsx
> +    {
done

2022-08-17 07:16 UTC, YBlas commented on packages/front_bo/src/pages/extra/centers.tsx
> +  {
done

2022-08-17 07:17 UTC, YBlas commented on packages/front_bo/src/pages/extra/centers.tsx
> +    <>
done

2022-08-17 07:23 UTC, avalero approved these changes

2022-08-17 07:24 UTC, YBlas commented on packages/front_bo/src/pages/extra/centers.tsx
> +                label: t("components.column.name"),
done

2022-08-17 07:24 UTC, YBlas commented on packages/front_bo/src/pages/extra/centers.tsx
> +                content: (item) => <div>{item.languages}</div>,
done

2022-08-17 08:11 UTC, merged