bugfix/AC-131
bq-educacion/academy-manager pull request #74
Opened 2022-08-23 13:09 UTC by pruizj

2022-08-23 15:21 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +            if (group !== undefined) return !groups.includes(group);
esto se suele poner `if(!group)`

2022-08-23 15:22 UTC, avalero requested changes

2022-08-23 15:22 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +            if (group !== undefined) return !groups.includes(group);
Has dicho que devuelve is group no esta definido, pero si lo está, qué devuelve?

2022-08-23 15:22 UTC, avalero commented on packages/api_bo/src/resolvers/mutation.ts
> +            if (group !== undefined) return !groups.includes(group);
no sé si lo que querrías poner es
```typescript
return !groups?.includes(group)
```

2022-08-23 15:37 UTC, pruizj commented on packages/api_bo/src/resolvers/mutation.ts
> +            if (group !== undefined) return !groups.includes(group);
Hecho que me he liado yo sola jajajaja. Quería poner que si está definido, porque si ponía  return !groups?.includes(group) me dice que group puede ser objectId o undifined

2022-08-24 09:37 UTC, aldaMarMu commented on packages/api_bo/src/resolvers/mutation.ts
>          id_group = (ids[0].id_group as number) + 1;
para asegurarnos que esto no se va a repetir nunca, añadiría que compruebe que no existe ese id_group en base de datos y si existiera, generar otro nuevo.

2022-08-24 10:15 UTC, pruizj commented on packages/api_bo/src/resolvers/mutation.ts
>          id_group = (ids[0].id_group as number) + 1;
Hecho

2022-08-24 10:45 UTC, aldaMarMu approved these changes

2022-08-24 10:53 UTC, aldaMarMu commented
@avalero, @pruizj no puede mergear por tu request changes pero ya ha aplicado los cambios que le dijiste.
Lo de esta PR lo necesita @YBlas, así que la mergeo yo :smile:

2022-08-24 10:53 UTC, merged