Bugs fixed
bq-educacion/academy-manager pull request #78
Opened 2022-08-29 11:09 UTC by YBlas

2022-08-29 15:43 UTC, CarmenDomin requested changes

2022-08-29 15:43 UTC, CarmenDomin commented on packages/ui/src/components/InputSuper.tsx
> +    font-style: italic;
El estilo de la fuente (que era el bug) está ya bien, pero el estilo del input deshabilitado todavía no es igual que en zeplin, el color del placeholder:
![image](https://user-images.githubusercontent.com/22561935/187234935-2590753e-25e2-4d9d-99da-39cee6421956.png)

![image](https://user-images.githubusercontent.com/22561935/187235051-447f876e-cacf-4c9f-8ba1-64b5a42057ff.png)

2022-08-29 15:43 UTC, CarmenDomin commented on packages/front_bo/src/pages/centers/index.tsx
> +        setLoadingAnimation(false);
Entiendo que con esto haces que el loading se muestre siempre al menos 1 segundo, porqué? que aporta?

2022-08-29 15:43 UTC, CarmenDomin commented on packages/front_bo/src/components/ContentStart.tsx
> +    height: 20px;
El scrollbar sigue sin estar bien, estoy abajo del todo de la tabla y lo veo así:
![image](https://user-images.githubusercontent.com/22561935/187237487-02a71e6d-0d91-4849-8476-53e19ee8d4f9.png)

Se arregla quitando este `height: 20px;`, porque esa línea lo que está haciendo esque los botones del scrollbar ocupen 20px de alto, eso está bien para el botón de arriba (para 'saltarse' el header) pero no para abajo.

Los botones son estos: 
![image](https://user-images.githubusercontent.com/22561935/187237706-22f549c0-ca63-4e96-9f2e-3ee48fb3160d.png)

He buscado cómo estilar de forma distinta esos botones y aunque parece que se puede no lo he logrado hacer funcionar.

2022-08-29 15:43 UTC, CarmenDomin commented on packages/front_bo/src/components/ContentStart.tsx
> +    height: 20px;
Otra cosa, en la demo se comentó que la barra de scroll tenía que verse en todos los lados donde hay scroll, para hacer eso puedes llevarte este código de `::-webkit-scrollbar` a `base-styles.ts`, y ponerlo en lugar de :
```
    ::-webkit-scrollbar {
      display: none;
    }
```

2022-08-29 15:49 UTC, CarmenDomin commented on packages/front_bo/src/components/ContentStart.tsx
> +    height: 20px;
Otra idea es esta:
```
    :not(.scrollbar)::-webkit-scrollbar {
      display: none;
    }
```
Con esto nada tendrá barra de scroll a noser que lleve la clase `scrollbar`. Y esa clase se la metes a la tabla y a las modales que lo necesiten

2022-08-30 09:36 UTC, YBlas commented on packages/front_bo/src/pages/centers/index.tsx
> +        setLoadingAnimation(false);
Lo hablé con Juanlu si prefería que no saliesen datos durante un ratín en lo que se cargaba o que apareciese la pantalla de carga, y dijo que prefería una pantalla de carga que durase por lo menos un segundo. Se puede cambiar si ves que desagiliza mucho

2022-08-30 10:26 UTC, YBlas commented on packages/ui/src/components/InputSuper.tsx
> +    font-style: italic;
done

2022-08-30 11:33 UTC, YBlas commented on packages/front_bo/src/components/ContentStart.tsx
> +    height: 20px;
done

2022-08-31 14:53 UTC, CarmenDomin approved these changes

2022-09-01 11:38 UTC, merged